### ISSUE TITLE
Has anyone tried using the cpu demo

### ISSUE THREAD

**Issue by jnngill** [lushaylabs/lushay-code#11]
Several demo's have "nextPnrGowinOptions": ["--enable-globals"] set in thevtangnano9k-series-examples\cpu\cpu.lushay.json
which fails saying 

Finished Synthesys
Starting PnR with NextPnR
    Error: unrecognised option '--enable-globals'
Finished PnR
Task finished with errors exiting
Toolchain Completed

**Comment by lushaylabs** [comment]
Thank you for reporting this, you are right this has been removed in newer versions, I will look into detecting and removing this from the execution based on the versino
