### ISSUE TITLE
Fail to generate bitstream on Tang Nano 9k - Buil only fails

### ISSUE THREAD

**Issue by mhanuel26** [lushaylabs/lushay-code#2]
Hi, 

After setting the toochain as described [here  ](https://learn.lushaylabs.com/getting-setup-with-the-tang-nano-9k/)
I am trying the build the uart example [here ](https://github.com/lushaylabs/tangnano9k-series-examples)

I am getting

![image](https://github.com/lushaylabs/lushay-code/assets/2257779/e4d11513-c14a-492d-85a3-209ccbee99f4)

I am not sure what might I have been missing, I know I have installed node.js which has installed the latest python 311 on my system.

Is that a python compatibility issue? If so, how can I use a different python along the FPGA toolchain?

WIll appreciate your help,
Thanks

**Comment by lushaylabs** [comment]
Hey, others have reported this same issue with the latest versions of OSs
cad suite, can you try using this version instead
https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2023-04-06

I will look into the issue further and see what the cause of the issue with
the new versions is

**Comment by mhanuel26** [comment]
Hi @lushaylabs ,

Thanks for you prompt answer. That works!
